<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Medge160" failures="2" tests="10" name="com.pg.tide.runnable.Runner" time="127.253" errors="0" timestamp="2022-07-29T05:07:40 GMT+05:30" skipped="1">
  <testcase classname="com.pg.tide.runnable.Runner" name="login" time="13.078">
    <failure message="System marked us as spam probably" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: System marked us as spam probably
at org.testng.Assert.fail(Assert.java:110)
at com.pg.tide.pageobjects.SignUpNowPGPage.login(SignUpNowPGPage.java:100)
at com.pg.tide.runnable.Runner.login(Runner.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="browseByNeedFebreze" time="9.364"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="registration" time="12.077">
    <failure message="User already registered" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User already registered
at org.testng.Assert.fail(Assert.java:110)
at com.pg.tide.pageobjects.SignUpNowPGPage.signUp(SignUpNowPGPage.java:44)
at com.pg.tide.runnable.Runner.registration(Runner.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- registration -->
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="startChat" time="9.122">
    <skipped/>
  </testcase> <!-- startChat -->
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="CustomStainCheck" time="7.681"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="checkPartCompanies" time="44.356"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="CalculateSavingsForSwitchingToColdWater" time="8.099"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="checkContactUsIframe" time="9.166"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="changeLanguage" time="7.778"/>
  <system-out/>
  <testcase classname="com.pg.tide.runnable.Runner" name="searchQuery" time="6.532"/>
  <system-out/>
</testsuite> <!-- com.pg.tide.runnable.Runner -->
